# Write your MySQL query statement below
SELECT PRODUCT_NAME, SUM(UNIT) UNIT
FROM  PRODUCTS P JOIN ORDERS O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE ORDER_DATE LIKE '2020-02-%'
GROUP BY P.PRODUCT_ID
HAVING SUM(UNIT) >= 100