# Write your MySQL query statement below
SELECT left(TRANS_DATE,7) MONTH, 
       COUNTRY, COUNT(STATE) TRANS_COUNT, 
       SUM(CASE WHEN STATE = 'APPROVED' THEN 1 ELSE 0 END) APPROVED_COUNT,
       SUM(AMOUNT) TRANS_TOTAL_AMOUNT,
       SUM(CASE WHEN STATE='APPROVED' THEN AMOUNT ELSE 0 END) APPROVED_TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY left(TRANS_DATE,7),COUNTRY