# Write your MySQL query statement below
SELECT A.MACHINE_ID, ROUND(AVG(B.TIMESTAMP - A.TIMESTAMP), 3) AS PROCESSING_TIME FROM
ACTIVITY A JOIN ACTIVITY B
ON A.MACHINE_ID = B.MACHINE_ID WHERE A.PROCESS_ID = B.PROCESS_ID
AND A.ACTIVITY_TYPE = 'START' AND B.ACTIVITY_TYPE = 'END'
GROUP BY 1